[package]
name = "aoc"
version = "0.1.0"
authors = ["Jan Kelemen"]
edition = "2021"

[lib]
name = "aoclib"
path = "src/lib/lib.rs"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
regex = "1.7.0"
lazy_static = "1.4.0"
md5 = "0.7.0"
